APT::FTPArchive::Release::Origin "Gitmas-Repo";
APT::FTPArchive::Release::Label "Gitmas";
APT::FTPArchive::Release::Suite "termux";
APT::FTPArchive::Release::Codename "packages";
APT::FTPArchive::Release::Architectures "aarch64";
APT::FTPArchive::Release::Components "main";
APT::FTPArchive::Release::Description "Jordan's Custom Micro-Utils";
